feta: typescript
yandex-cloud/yfm-transform pull request #122
Opened 2022-01-25 08:54 UTC by smsochneg

2022-01-26 10:07 UTC, Postamentovich approved these changes

2022-01-26 10:32 UTC, burashka requested changes
Хочу собрать потестить руками.

2022-02-02 16:56 UTC, burashka commented
yfmlint на выходе потерялся. В src ты его перенес. А после сборки его похоже нет

2022-02-02 16:58 UTC, burashka commented
links тоже потерялись. Попробуй взять [yfm-docs](https://github.com/yandex-cloud/yfm-docs), подложить ему выхлоп и собрать. Это основной сценарий использования yfm-transform сейчас. И там TS, заодно типы проверим.

2022-02-15 11:08 UTC, smsochneg commented
@burashka

2022-02-16 17:16 UTC, burashka commented
require заработал, но нужно писать .default. Что все-равно ломает обратную совместимость. Может совсем выправить? В худшем случае у меня сработал костыль сделать не генеренный файл, который подключит с default и экспортнет по старому:
```
const transform = require('./index').default;

module.exports = transform;
```

2022-02-16 17:16 UTC, burashka commented
dist соберет на самом деле всё. И transform тоже. Я бы переименовал, не очевидно, по-моему. Ожидал что build соберет всё. По идее просто dist теперь и не нужен же.

2022-02-16 17:17 UTC, burashka commented
В yfm-docs есть папочка tests. В ней отдельный package.json. Можно поставить там пакеты и запустить тесты. Если подложить собранный из этого ПР yfm-transform, то часть тестов падают.

![Выделение_977](https://user-images.githubusercontent.com/2195887/154320011-5eaeb0cd-a535-435b-8e3c-ac9ed157829d.jpg)

2022-02-21 06:44 UTC, smsochneg commented on package.json
> +    "typecheck": "tsc -p tsconfig.json --noEmit",
👍

2022-02-23 10:15 UTC, burashka approved these changes

2022-02-23 10:15 UTC, merged